plugins {
    `java-gradle-plugin`
    `maven-publish`
    signing
    kotlin("jvm") version "2.1.0"
    id("org.jetbrains.dokka") version "1.9.20"
    id("io.github.gradle-nexus.publish-plugin") version "2.0.0"
}

group = property("GROUP") as String

val versionBase = file("version.txt").readText().trim()
version = if (System.getenv("RELEASE")?.toBoolean() == true) versionBase else "$versionBase-SNAPSHOT"

println("Build version $version")
println("Release build: ${System.getenv("RELEASE")?.toBoolean() == true}")

java {
    sourceCompatibility = JavaVersion.VERSION_11
    targetCompatibility = JavaVersion.VERSION_11
}

// Maven Central requires sources and javadoc JARs. Sources JAR is empty to
// avoid leaking proprietary source code. Javadoc JAR is generated by Dokka
// from KDoc comments on public classes/methods — useful for IDE IntelliSense.
val dokkaJavadocJar by tasks.registering(Jar::class) {
    dependsOn(tasks.named("dokkaJavadoc"))
    from(tasks.named("dokkaJavadoc").map { it.outputs })
    archiveClassifier.set("javadoc")
}
val emptySourcesJar by tasks.registering(Jar::class) {
    archiveClassifier.set("sources")
}

kotlin {
    jvmToolchain(11)
}

repositories {
    mavenCentral()
    google()
}

dependencies {
    compileOnly("com.android.tools.build:gradle-api:8.6.0")
    compileOnly("com.android.tools.build:gradle:8.6.0")
    compileOnly("org.jetbrains.kotlin:kotlin-gradle-plugin-api:2.1.0")
    implementation("org.apache.httpcomponents:httpclient:4.5.14")
    implementation("org.apache.httpcomponents:httpmime:4.5.14")
    implementation("org.json:json:20240303")

    // ASM tree + analysis used by the app-startup-tracing production
    // transforms (MethodNode-based rewrite, Analyzer/BasicInterpreter
    // for natural-loop detection). compileOnly — AGP brings the same
    // ASM 9.7 transitively at plugin runtime through its R8/transform
    // toolchain, so packaging another copy would risk classloader
    // pollution.
    //
    // **AGP→ASM version coupling.** AGP 8.6.0 (the version this plugin
    // is built against) pulls ASM 9.7 transitively via its R8/transform
    // chain (`com.android.tools.build:gradle:8.6.0` → `transform-api`
    // → `org.ow2.asm:asm-*:9.7`). Consumers MUST use AGP 8.6.0+ at
    // build time; earlier AGP releases shipped older ASM versions
    // (e.g. AGP 8.4 ships ASM 9.5) that lack a few utility methods
    // this plugin doesn't use today but is one refactor away from
    // depending on. If the plugin ever drops to a Method/Class API
    // added in ASM 9.6+, surface the minimum AGP requirement in the
    // plugin's POM constraint instead of relying on this comment.
    compileOnly("org.ow2.asm:asm-tree:9.7")
    compileOnly("org.ow2.asm:asm-analysis:9.7")

    testImplementation(kotlin("test"))
    testImplementation("junit:junit:4.13.2")

    // ASM toolchain used by the app-startup-tracing test harness
    // (CheckClassAdapter for verifier-compatibility assertions, Analyzer
    // for CFG-correctness assertions, tree + core for transform code).
    testImplementation("org.ow2.asm:asm:9.7")
    testImplementation("org.ow2.asm:asm-tree:9.7")
    testImplementation("org.ow2.asm:asm-util:9.7")
    testImplementation("org.ow2.asm:asm-analysis:9.7")

    // Kotlin compiler embeddable for the test harness's Kotlin-source
    // compiler (compiles inline Kotlin snippets to class bytes that the
    // ASM harness then transforms).
    testImplementation("org.jetbrains.kotlin:kotlin-compiler-embeddable:2.1.0")
}

// ============================================================================
// integrationTest — TestKit-driven build-time tests
//
// Why a separate source set: TestKit launches a fresh Gradle daemon per
// fixture build (5-15s warm, 30-60s cold), so folding these into the
// existing `test` task would balloon the inner-loop unit suite from
// ~10s to several minutes. The fast unit-test loop is a real productivity
// feature worth preserving.
//
// Wired into `check` so CI runs both layers; not wired into `test` so
// `./gradlew test` stays fast for developers.
// ============================================================================

val integrationTest: SourceSet = sourceSets.create("integrationTest") {
    // Kotlin source dirs (`src/integrationTest/kotlin`) and resource dirs
    // (`src/integrationTest/resources`) are auto-wired by the `kotlin("jvm")`
    // plugin convention. Adding them explicitly here causes
    // `processIntegrationTestResources` to see each resource entry twice.
    compileClasspath += sourceSets["main"].output + configurations["testRuntimeClasspath"]
    runtimeClasspath += output + compileClasspath
}

configurations.named("integrationTestImplementation") {
    extendsFrom(configurations["testImplementation"])
}
configurations.named("integrationTestRuntimeOnly") {
    extendsFrom(configurations["testRuntimeOnly"])
}

dependencies {
    "integrationTestImplementation"(gradleTestKit())
}

// Stub-SDK jar packaging task — compiles `src/integrationTest/stub-sdk-src/*.java`
// into a tiny jar that the fixture project pins as `compileOnly`. Mirrors the
// SDK's locked Bugsee*Dispatcher/Trace contracts; any drift surfaces as a
// compile error here at integration-test time. Built fresh each run (~1s).
val stubSdkClassesDir = layout.buildDirectory.dir("integrationTest/stub-sdk/classes")
val stubSdkJarDir = layout.buildDirectory.dir("integrationTest/stub-sdk")

val compileStubSdk by tasks.registering(JavaCompile::class) {
    description = "Compile stub-SDK source for integrationTest fixture."
    group = "verification"
    source = fileTree("src/integrationTest/stub-sdk-src")
    destinationDirectory.set(stubSdkClassesDir)
    classpath = files()
    sourceCompatibility = "1.8"
    targetCompatibility = "1.8"
    options.release.set(8)
    options.encoding = "UTF-8"
}

val buildStubSdkJar by tasks.registering(Jar::class) {
    description = "Bundle stub-SDK classes into a jar consumable by fixture projects."
    group = "verification"
    dependsOn(compileStubSdk)
    archiveFileName.set("bugsee-stub.jar")
    destinationDirectory.set(stubSdkJarDir)
    from(stubSdkClassesDir)
}

// Publish the stub jar to a local Maven repo under build/integrationTest/stub-sdk-repo
// using the real `com.bugsee:bugsee-android:1.0.0` coordinates. The fixture
// declares this as `compileOnly("com.bugsee:bugsee-android:1.0.0")` so the
// plugin's `DependencyDetector.hasBugseeDependency(...)` recognizes the dep
// (it matches on group=com.bugsee + name starts-with "bugsee-android") and
// proceeds to register the AppStartupTracing transform.
val stubSdkRepoDir = layout.buildDirectory.dir("integrationTest/stub-sdk-repo")
val publishStubSdkToLocalRepo by tasks.registering(Copy::class) {
    description = "Publish the stub-SDK jar under com.bugsee:bugsee-android:1.0.0 to a local repo."
    group = "verification"
    dependsOn(buildStubSdkJar)
    val artifactDir = stubSdkRepoDir.map { it.dir("com/bugsee/bugsee-android/1.0.0") }
    from(buildStubSdkJar.flatMap { it.archiveFile })
    into(artifactDir)
    rename { "bugsee-android-1.0.0.jar" }
    doLast {
        // Minimal POM — the plugin's dependency detector only reads
        // group/name/version, but Gradle's POM-strict resolution wants the
        // file to exist and parse.
        artifactDir.get().asFile.resolve("bugsee-android-1.0.0.pom").writeText(
            """<?xml version="1.0" encoding="UTF-8"?>
            |<project xmlns="http://maven.apache.org/POM/4.0.0">
            |  <modelVersion>4.0.0</modelVersion>
            |  <groupId>com.bugsee</groupId>
            |  <artifactId>bugsee-android</artifactId>
            |  <version>1.0.0</version>
            |  <packaging>jar</packaging>
            |</project>
            """.trimMargin()
        )
    }
}

// Pre-resolve a JDK 17 launcher at configure time so we can forward its
// installation path to TestKit's fixture build (AGP 8.6 requires JDK 17 at
// daemon runtime, even though the plugin itself builds against JDK 11).
val launcher17Provider = javaToolchains.launcherFor {
    languageVersion.set(JavaLanguageVersion.of(17))
}

// Note: the fixture build sources this plugin via
// `pluginManagement.includeBuild(...)` (see
// `src/integrationTest/resources/fixtures/.../settings.gradle.kts`)
// instead of TestKit's `withPluginClasspath()`. That way the plugin
// under test loads into the SAME classloader as AGP and the Kotlin
// Gradle Plugin API — the buildscript classloader — avoiding
// cross-classloader `NoClassDefFoundError` against `SingleArtifact` /
// `KotlinCompilerPluginSupportPlugin` when Gradle's plugin verifier
// resolves Bugsee plugin class references.

tasks.register<Test>("integrationTest") {
    description = "TestKit-driven build-time integration tests for the Bugsee Android Gradle plugin."
    group = "verification"
    testClassesDirs = integrationTest.output.classesDirs
    classpath = integrationTest.runtimeClasspath
    dependsOn(buildStubSdkJar)
    dependsOn(publishStubSdkToLocalRepo)
    useJUnit()
    // Forward the local stub-SDK Maven repo path so the fixture's
    // `settings.gradle.kts` can wire it via
    // `repositoriesMode { … repositories { maven { url = … } } }`.
    systemProperty(
        "bugsee.testkit.stubSdkRepo",
        stubSdkRepoDir.get().asFile.absolutePath
    )
    // Forward the project dir so tests can resolve the fixture resources
    // root from the integrationTest source set.
    systemProperty("bugsee.testkit.pluginProjectDir", project.projectDir.absolutePath)
    // Forward JDK 17 JAVA_HOME for the fixture build's daemon.
    systemProperty(
        "bugsee.testkit.javaHome",
        launcher17Provider.get().metadata.installationPath.asFile.absolutePath
    )
    // Large heap — TestKit + AGP daemons are memory-hungry.
    maxHeapSize = "2g"
}

// Integration tests are opt-in: `./gradlew build` runs the fast unit suite
// only. To include the TestKit-driven integration tier in `check`/`build`,
// pass `-Pbugsee.runIntegrationTests=true` (or run `./gradlew integrationTest`
// directly, or use `./scripts/build.sh --full`). Mirrors the SDK's
// `./scripts/test.sh` split between fast unit tests and slow on-device tests
// — both projects keep the inner dev loop quick by default.
if (project.findProperty("bugsee.runIntegrationTests") == "true") {
    tasks.named("check") {
        dependsOn("integrationTest")
    }
}

// Generate version resource so the plugin can read its own version at runtime.
// Must include the -SNAPSHOT suffix when applicable.
tasks.named<Copy>("processResources") {
    val fullVersion = version.toString()
    from("version.txt") {
        rename { "bugsee-plugin-version.txt" }
        filter { fullVersion }
    }
    // Minimum compatible Bugsee Android SDK version. Used by the plugin's
    // dependency auto-add logic to pull in the core SDK when the consuming
    // app does not declare it. Plain pass-through; no filtering.
    from("sdk-min-version.txt") {
        rename { "bugsee-sdk-min-version.txt" }
    }
}

gradlePlugin {
    plugins {
        create("bugsee") {
            id = "com.bugsee.android.gradle"
            implementationClass = "com.bugsee.android.gradle.BugseePlugin"
            displayName = property("POM_NAME") as String
            description = property("POM_DESCRIPTION") as String
        }
    }
}

// Publishing configuration

fun getRepositoryUsername(): String =
    if (hasProperty("NEXUS_USERNAME")) property("NEXUS_USERNAME") as String else ""

fun getRepositoryPassword(): String =
    if (hasProperty("NEXUS_PASSWORD")) property("NEXUS_PASSWORD") as String else ""

// POM metadata required by Maven Central
fun MavenPublication.configurePom() {
    pom {
        name.set(property("POM_NAME") as String)
        description.set(property("POM_DESCRIPTION") as String)
        url.set(property("POM_URL") as String)

        licenses {
            license {
                name.set("Proprietary")
                url.set("https://bugsee.com/tos/")
            }
        }
        developers {
            developer {
                id.set("bugsee")
                name.set("Bugsee, Inc")
                email.set("support@bugsee.com")
            }
        }
        scm {
            url.set("https://bugsee.com/")
        }
    }
}

publishing {
    publications.withType<MavenPublication>().configureEach {
        if (name == "pluginMaven") {
            artifactId = property("POM_ARTIFACT_ID") as String
        }
        artifact(emptySourcesJar)
        artifact(dokkaJavadocJar)
        configurePom()
    }
}

nexusPublishing {
    repositories {
        sonatype {
            nexusUrl.set(uri("https://ossrh-staging-api.central.sonatype.com/service/local/"))
            snapshotRepositoryUrl.set(uri("https://central.sonatype.com/repository/maven-snapshots/"))
            username = getRepositoryUsername()
            password = getRepositoryPassword()
        }
    }
}

signing {
    isRequired = false
    sign(publishing.publications)
}

// `enabled = …` (not `onlyIf`) so Gradle skips the task wholesale —
// including its built-in `onlyIf("Signing is required, or signatory is
// set", …)` spec whose lazy `getSignatory()` call throws under certain
// Gradle 8.7+ no-credentials shapes instead of returning null. With
// `onlyIf` alone we'd still reach that throwing spec on every local
// publish.
tasks.withType<Sign>().configureEach {
    enabled = !version.toString().contains("SNAPSHOT") && project.hasProperty("signing.keyId")
}

// Fix task dependency: marker publication must depend on the signing task
// for the main pluginMaven publication (known Gradle issue with
// java-gradle-plugin + signing + custom artifacts).
tasks.withType<PublishToMavenRepository>().configureEach {
    dependsOn(tasks.withType<Sign>())
}
tasks.withType<PublishToMavenLocal>().configureEach {
    dependsOn(tasks.withType<Sign>())
}
