apply plugin: 'groovy'
apply plugin: 'maven-publish'
apply from: 'maven-push.gradle'

group = 'com.bugsee.android'
version = '1.0.0'

repositories {
    mavenCentral()
    google()
}

//publishing {
//    publications {
//        BugseePlugin(MavenPublication) {
//            from components.java
//        }
//    }
//
//    // Publish to local directory
//    repositories {
//        maven {
//            name = 'localRepo'
//            url = layout.buildDirectory.dir("repo")
//        }
//    }
//}

dependencies {

    implementation gradleApi()
    implementation localGroovy()
    implementation 'org.apache.httpcomponents:httpclient:4.5.13'
    implementation 'org.apache.httpcomponents:httpmime:4.5.13'
    implementation 'com.android.tools.build:gradle:4.2.2'
    implementation 'commons-io:commons-io:2.11.0'

}

def buildShaCommand = "git --git-dir=" + projectDir + "/.git rev-parse --short HEAD";

ext {
    File versionFile = file("${projectDir}/version.txt")
    versionName = versionFile.readLines()[0].trim()
    buildSha = buildShaCommand.execute().text.trim()

    Properties properties = new Properties()
    releaseBuild = System.env.RELEASE ? System.env.RELEASE.toBoolean() : false

    if (releaseBuild) {
    } else {
        versionName = versionName + "-SNAPSHOT"
    }
    println 'Build version ' + versionName
    println 'Release build:' + releaseBuild
}
