plugins {
    id 'groovy'
    id 'maven-publish'
    id 'java-gradle-plugin'

    // This dep is much more flexible, but requires Java 11
    // and Gradle/AGP 8+
    // id "com.vanniktech.maven.publish" version "0.29.0"
}

apply from: 'maven-push.gradle'

group = GROUP
version = getVersionName()

repositories {
    mavenCentral()
    google()
}

dependencies {
    implementation gradleApi()
    implementation localGroovy()
    implementation 'org.apache.httpcomponents:httpclient:4.5.14'
    implementation 'org.apache.httpcomponents:httpmime:4.5.14'
    implementation 'com.android.tools.build:gradle:4.2.2'
    implementation 'commons-io:commons-io:2.11.0'
}

gradlePlugin {
    plugins {
        bugsee {
            id = 'com.bugsee.android.gradle'
            implementationClass = 'com.bugsee.android.gradle.BugseePlugin'
            displayName = POM_NAME
        }
    }
}

def buildShaCommand = "git --git-dir=" + projectDir + "/.git rev-parse --short HEAD";

ext {
    versionName = getVersionName()
    buildSha = buildShaCommand.execute().text.trim()

    Properties properties = new Properties()
    releaseBuild = System.env.RELEASE ? System.env.RELEASE.toBoolean() : false

    if (releaseBuild) {
    } else {
        versionName = versionName + "-SNAPSHOT"
    }
    println 'Build version ' + versionName
    println 'Release build:' + releaseBuild
}


def getVersionName() {
    File versionFile = file("${projectDir}/version.txt")
    return versionFile.readLines()[0].trim()
}
