plugins {
    `java-gradle-plugin`
    `maven-publish`
    signing
    kotlin("jvm") version "2.1.0"
    id("org.jetbrains.dokka") version "1.9.20"
    id("io.github.gradle-nexus.publish-plugin") version "2.0.0"
}

group = property("GROUP") as String

val versionBase = file("version.txt").readText().trim()
version = if (System.getenv("RELEASE")?.toBoolean() == true) versionBase else "$versionBase-SNAPSHOT"

println("Build version $version")
println("Release build: ${System.getenv("RELEASE")?.toBoolean() == true}")

java {
    sourceCompatibility = JavaVersion.VERSION_11
    targetCompatibility = JavaVersion.VERSION_11
}

// Maven Central requires sources and javadoc JARs. Sources JAR is empty to
// avoid leaking proprietary source code. Javadoc JAR is generated by Dokka
// from KDoc comments on public classes/methods — useful for IDE IntelliSense.
val dokkaJavadocJar by tasks.registering(Jar::class) {
    dependsOn(tasks.named("dokkaJavadoc"))
    from(tasks.named("dokkaJavadoc").map { it.outputs })
    archiveClassifier.set("javadoc")
}
val emptySourcesJar by tasks.registering(Jar::class) {
    archiveClassifier.set("sources")
}

kotlin {
    jvmToolchain(11)
}

repositories {
    mavenCentral()
    google()
}

dependencies {
    compileOnly("com.android.tools.build:gradle-api:8.6.0")
    compileOnly("com.android.tools.build:gradle:8.6.0")
    compileOnly("org.jetbrains.kotlin:kotlin-gradle-plugin-api:2.1.0")
    implementation("org.apache.httpcomponents:httpclient:4.5.14")
    implementation("org.apache.httpcomponents:httpmime:4.5.14")
    implementation("org.json:json:20240303")

    // ASM tree + analysis used by the app-startup-tracing production
    // transforms (MethodNode-based rewrite, Analyzer/BasicInterpreter
    // for natural-loop detection). compileOnly — AGP brings the same
    // ASM 9.7 transitively at plugin runtime through its R8/transform
    // toolchain, so packaging another copy would risk classloader
    // pollution.
    //
    // **AGP→ASM version coupling.** AGP 8.6.0 (the version this plugin
    // is built against) pulls ASM 9.7 transitively via its R8/transform
    // chain (`com.android.tools.build:gradle:8.6.0` → `transform-api`
    // → `org.ow2.asm:asm-*:9.7`). Consumers MUST use AGP 8.6.0+ at
    // build time; earlier AGP releases shipped older ASM versions
    // (e.g. AGP 8.4 ships ASM 9.5) that lack a few utility methods
    // this plugin doesn't use today but is one refactor away from
    // depending on. If the plugin ever drops to a Method/Class API
    // added in ASM 9.6+, surface the minimum AGP requirement in the
    // plugin's POM constraint instead of relying on this comment.
    compileOnly("org.ow2.asm:asm-tree:9.7")
    compileOnly("org.ow2.asm:asm-analysis:9.7")

    testImplementation(kotlin("test"))
    testImplementation("junit:junit:4.13.2")

    // ASM toolchain used by the app-startup-tracing test harness
    // (CheckClassAdapter for verifier-compatibility assertions, Analyzer
    // for CFG-correctness assertions, tree + core for transform code).
    testImplementation("org.ow2.asm:asm:9.7")
    testImplementation("org.ow2.asm:asm-tree:9.7")
    testImplementation("org.ow2.asm:asm-util:9.7")
    testImplementation("org.ow2.asm:asm-analysis:9.7")

    // Kotlin compiler embeddable for the test harness's Kotlin-source
    // compiler (compiles inline Kotlin snippets to class bytes that the
    // ASM harness then transforms).
    testImplementation("org.jetbrains.kotlin:kotlin-compiler-embeddable:2.1.0")
}

// Generate version resource so the plugin can read its own version at runtime.
// Must include the -SNAPSHOT suffix when applicable.
tasks.named<Copy>("processResources") {
    val fullVersion = version.toString()
    from("version.txt") {
        rename { "bugsee-plugin-version.txt" }
        filter { fullVersion }
    }
    // Minimum compatible Bugsee Android SDK version. Used by the plugin's
    // dependency auto-add logic to pull in the core SDK when the consuming
    // app does not declare it. Plain pass-through; no filtering.
    from("sdk-min-version.txt") {
        rename { "bugsee-sdk-min-version.txt" }
    }
}

gradlePlugin {
    plugins {
        create("bugsee") {
            id = "com.bugsee.android.gradle"
            implementationClass = "com.bugsee.android.gradle.BugseePlugin"
            displayName = property("POM_NAME") as String
            description = property("POM_DESCRIPTION") as String
        }
    }
}

// Publishing configuration

fun getRepositoryUsername(): String =
    if (hasProperty("NEXUS_USERNAME")) property("NEXUS_USERNAME") as String else ""

fun getRepositoryPassword(): String =
    if (hasProperty("NEXUS_PASSWORD")) property("NEXUS_PASSWORD") as String else ""

// POM metadata required by Maven Central
fun MavenPublication.configurePom() {
    pom {
        name.set(property("POM_NAME") as String)
        description.set(property("POM_DESCRIPTION") as String)
        url.set(property("POM_URL") as String)

        licenses {
            license {
                name.set("Proprietary")
                url.set("https://bugsee.com/tos/")
            }
        }
        developers {
            developer {
                id.set("bugsee")
                name.set("Bugsee, Inc")
                email.set("support@bugsee.com")
            }
        }
        scm {
            url.set("https://bugsee.com/")
        }
    }
}

publishing {
    publications.withType<MavenPublication>().configureEach {
        if (name == "pluginMaven") {
            artifactId = property("POM_ARTIFACT_ID") as String
        }
        artifact(emptySourcesJar)
        artifact(dokkaJavadocJar)
        configurePom()
    }
}

nexusPublishing {
    repositories {
        sonatype {
            nexusUrl.set(uri("https://ossrh-staging-api.central.sonatype.com/service/local/"))
            snapshotRepositoryUrl.set(uri("https://central.sonatype.com/repository/maven-snapshots/"))
            username = getRepositoryUsername()
            password = getRepositoryPassword()
        }
    }
}

signing {
    isRequired = false
    sign(publishing.publications)
}

// `enabled = …` (not `onlyIf`) so Gradle skips the task wholesale —
// including its built-in `onlyIf("Signing is required, or signatory is
// set", …)` spec whose lazy `getSignatory()` call throws under certain
// Gradle 8.7+ no-credentials shapes instead of returning null. With
// `onlyIf` alone we'd still reach that throwing spec on every local
// publish.
tasks.withType<Sign>().configureEach {
    enabled = !version.toString().contains("SNAPSHOT") && project.hasProperty("signing.keyId")
}

// Fix task dependency: marker publication must depend on the signing task
// for the main pluginMaven publication (known Gradle issue with
// java-gradle-plugin + signing + custom artifacts).
tasks.withType<PublishToMavenRepository>().configureEach {
    dependsOn(tasks.withType<Sign>())
}
tasks.withType<PublishToMavenLocal>().configureEach {
    dependsOn(tasks.withType<Sign>())
}
