plugins {
    `java-gradle-plugin`
    `maven-publish`
    signing
    kotlin("jvm") version "2.1.0"
    id("org.jetbrains.dokka") version "1.9.20"
    id("io.github.gradle-nexus.publish-plugin") version "2.0.0"
}

group = property("GROUP") as String

val versionBase = file("version.txt").readText().trim()
version = if (System.getenv("RELEASE")?.toBoolean() == true) versionBase else "$versionBase-SNAPSHOT"

println("Build version $version")
println("Release build: ${System.getenv("RELEASE")?.toBoolean() == true}")

java {
    sourceCompatibility = JavaVersion.VERSION_11
    targetCompatibility = JavaVersion.VERSION_11
}

// Maven Central requires sources and javadoc JARs. Sources JAR is empty to
// avoid leaking proprietary source code. Javadoc JAR is generated by Dokka
// from KDoc comments on public classes/methods — useful for IDE IntelliSense.
val dokkaJavadocJar by tasks.registering(Jar::class) {
    dependsOn(tasks.named("dokkaJavadoc"))
    from(tasks.named("dokkaJavadoc").map { it.outputs })
    archiveClassifier.set("javadoc")
}
val emptySourcesJar by tasks.registering(Jar::class) {
    archiveClassifier.set("sources")
}

kotlin {
    jvmToolchain(11)
}

repositories {
    mavenCentral()
    google()
}

dependencies {
    compileOnly("com.android.tools.build:gradle-api:8.6.0")
    compileOnly("com.android.tools.build:gradle:8.6.0")
    compileOnly("org.jetbrains.kotlin:kotlin-gradle-plugin-api:2.1.0")
    implementation("org.apache.httpcomponents:httpclient:4.5.14")
    implementation("org.apache.httpcomponents:httpmime:4.5.14")
    implementation("org.json:json:20240303")
    testImplementation(kotlin("test"))
    testImplementation("junit:junit:4.13.2")
}

// Generate version resource so the plugin can read its own version at runtime.
// Must include the -SNAPSHOT suffix when applicable.
tasks.named<Copy>("processResources") {
    val fullVersion = version.toString()
    from("version.txt") {
        rename { "bugsee-plugin-version.txt" }
        filter { fullVersion }
    }
}

gradlePlugin {
    plugins {
        create("bugsee") {
            id = "com.bugsee.android.gradle"
            implementationClass = "com.bugsee.android.gradle.BugseePlugin"
            displayName = property("POM_NAME") as String
            description = property("POM_DESCRIPTION") as String
        }
    }
}

// Publishing configuration

fun getRepositoryUsername(): String =
    if (hasProperty("NEXUS_USERNAME")) property("NEXUS_USERNAME") as String else ""

fun getRepositoryPassword(): String =
    if (hasProperty("NEXUS_PASSWORD")) property("NEXUS_PASSWORD") as String else ""

// POM metadata required by Maven Central
fun MavenPublication.configurePom() {
    pom {
        name.set(property("POM_NAME") as String)
        description.set(property("POM_DESCRIPTION") as String)
        url.set(property("POM_URL") as String)

        licenses {
            license {
                name.set("Proprietary")
                url.set("https://bugsee.com/tos/")
            }
        }
        developers {
            developer {
                id.set("bugsee")
                name.set("Bugsee, Inc")
                email.set("support@bugsee.com")
            }
        }
        scm {
            url.set("https://bugsee.com/")
        }
    }
}

publishing {
    publications.withType<MavenPublication>().configureEach {
        if (name == "pluginMaven") {
            artifactId = property("POM_ARTIFACT_ID") as String
        }
        artifact(emptySourcesJar)
        artifact(dokkaJavadocJar)
        configurePom()
    }
}

nexusPublishing {
    repositories {
        sonatype {
            nexusUrl.set(uri("https://ossrh-staging-api.central.sonatype.com/service/local/"))
            snapshotRepositoryUrl.set(uri("https://central.sonatype.com/repository/maven-snapshots/"))
            username = getRepositoryUsername()
            password = getRepositoryPassword()
        }
    }
}

signing {
    isRequired = false
    sign(publishing.publications)
}

tasks.withType<Sign>().configureEach {
    onlyIf {
        !version.toString().contains("SNAPSHOT") && project.hasProperty("signing.keyId")
    }
}

// Fix task dependency: marker publication must depend on the signing task
// for the main pluginMaven publication (known Gradle issue with
// java-gradle-plugin + signing + custom artifacts).
tasks.withType<PublishToMavenRepository>().configureEach {
    dependsOn(tasks.withType<Sign>())
}
tasks.withType<PublishToMavenLocal>().configureEach {
    dependsOn(tasks.withType<Sign>())
}
