apply plugin: 'groovy'
apply plugin: 'maven'

uploadArchives {
    repositories {
        mavenDeployer {
            pom.artifactId = 'gradle-plugin'
            repository(url: "file://maven")
        }
    }
}

group = 'com.bugsee.android'
version = '1.0.0'

dependencies {
  repositories {
    mavenCentral()
  }

  compile gradleApi()
  compile localGroovy()
  compile 'com.android.tools.build:gradle:1.0.0'
  compile 'org.apache.httpcomponents:httpclient:4.3.6'
  compile 'org.apache.httpcomponents:httpmime:4.3.6'
}
