GROUP=com.bugsee
POM_ARTIFACT_ID=bugsee-android-gradle-plugin

POM_NAME=Bugsee Android Gradle Plugin
POM_DESCRIPTION=Gradle plugin for Bugsee to automatically upload ProGuard mapping files and instrument OkHttp
POM_URL=https://www.bugsee.com

POM_DEVELOPER_NAME=Bugsee, Inc.
POM_DEVELOPER_URL=https://www.bugsee.com

POM_PACKAGING=jar
